var Lista2 = [
  { name: "📺Aida Tv", url: "https://lamovie.github.io/AIDA-TV/" },
  { name: "📺South Park Tv", url: "https://pluto.tv/es/live-tv/south-park-pvt2/details" },
  { name: "📺Bum Tv", url: "https://movil.ejeserver.com/live/visiondorada.m3u8" },
  { name: "📺Lilo y Stitch Tv", url: "https://cloudvideo.servers10.com:8081/impactotv/index.m3u8" },
  { name: "📺Activa Tv", url: "https://streamtv.mediasector.es/hls/activatv/index.m3u8"}, 
  { name: "📺Vevo R&B Tv", url: "https://is.gd/FLLYMV"}, 
  { name: "📺4Fun Tv", url: "https://stream.4fun.tv:8888/hls/4f.m3u8"}, 
  { name: "📺Bob Esponja Tv", url: "https://is.gd/O95aRO"}, 
  { name: "📺Anime Tv", url: "https://is.gd/ZbUCIE"}, 
  { name: "📺Cine Terror Tv", url: "https://is.gd/GyYDz0"}, 
  { name: "📺Vevo 90s Tv", url: "https://is.gd/qONOfE"}, 
  { name: "📺Series Tv", url: "https://is.gd/tit1cW"}, 
  { name: "📺Studio Delta Tv", url: "https://5ce9406b73c33.streamlock.net/RSD/ngrp:livestream_all/playlist.m3u8"}, 
  { name: "📺Toons Tv", url: "https://is.gd/Y01en3"}, 
  { name: "📺Comedy Center Tv", url: "https://is.gd/AV8Q3O"}, 
  { name: "📺GH Tv", url: "https://tv.ghtelevision.com:3018/live/ghtelevisionlive.m3u8"}, 
  { name: "📺El Hormiguero Tv", url: "https://fast-channels.atresmedia.com/648ef5882bfab0e4627e0d61/648ef5882bfab0e4627e0d61.m3u8"}, 
  { name: "📺Classic Tv", url: "https://is.gd/7CaWXu"},
  { name: "⚙️Sofia 1", url: "https://drive.google.com/drive/folders/1-1XNTcBjHMPOia_zXKWZNhdQQUe2SaNE" },
  { name: "⚙️Sofia 2", url: "https://drive.google.com/drive/folders/1-1wPR4nf8fmRQ-HNQvkfP0H1HJHxm6yb" },
  { name: "⚙️Sofia 3", url: "https://drive.google.com/drive/folders/1DgwNQiBR3xvrI3yOgw4Wlv4uUCZxugmf" },
  { name: "💻Curso HTML", url: "https://drive.google.com/drive/folders/1Gafbr3mBA4sRq9ciwS1fiCDX5T11YdzH" },
  { name: "🍿American Assassin", url: "https://drive.google.com/file/d/1mOP_DRpFgyNSdd-r0mXRzBdTZtBjHB0y/view?usp=drive_link" },
  { name: "🍿Ava", url: "https://drive.google.com/file/d/1kgaSmxkrcj8SEPxlckzZXEA7UnkoGsNO/view?usp=drive_link" },
  { name: "🍿Avengers Infinity War", url: "https://drive.google.com/file/d/1-gXd9TdFVBByPuy_i-0NSbjBTd18xVQC/view?usp=drive_link" },
  { name: "🍿Delirium (Nany)", url: "https://drive.google.com/file/d/1pHjKsVpVFYM92jHdFXP9lBKhF3IaKcPH/view?usp=drive_link" },
  { name: "🍿Extraction 1", url: "https://drive.google.com/file/d/1mVRTgcWkCywQENX-re4PG_3DvOmzU21Z/view?usp=drive_link" },
  { name: "🍿Free Guys", url: "https://drive.google.com/file/d/1-5W4M0kgXPcvnkvx2PwoFzzYIG_W_Plu/view?usp=drive_link" },
  { name: "🍿Fuerza Trueno", url: "https://drive.google.com/file/d/1nxcaUTm0Fci7yY9yhtJyUG4wJrE1b4a8/view?usp=drive_link" },
  { name: "🍿Infinite", url: "https://drive.google.com/file/d/1-XRFN8AjnrkBCAeUInUGV0k-C-uy0HDy/view?usp=drive_link" },
  { name: "🍿Johnny English", url: "https://drive.google.com/file/d/1mX1EBJ6wfmwb45W29l-AAOrurfLEwaL9/view?usp=drive_link" },
  { name: "🍿La Niñera 1", url: "https://drive.google.com/file/d/1jh7gB7ZXG8wkcBqJa1pPUe2jjqHoybsU/view?usp=drive_link" },
  { name: "🍿La Niñera 2", url: "https://drive.google.com/file/d/1kZAO86MGTRcyc3wQgmxCQ0zrSnvE2hZr/view?usp=drive_link" },
  { name: "🍿South Park 2 Post Covid", url: "https://drive.google.com/file/d/1CI1O3RKbDvXONw8JgADdo6sv8FlqbuOT/view?usp=drive_link" },
  { name: "🍿Thor Ragnarok", url: "https://drive.google.com/file/d/11lf6dy_MSUu29tLvMHtbNebRx0k2uVZU/view?usp=drive_link" },
  { name: "🍿X Men Dark Phoenix", url: "https://drive.google.com/file/d/1G8uArYwuTj4z3kraYUuOHT-fJ87DlPfT/view?usp=drive_link" },
  { name: "🍿El Rito", url: "https://drive.google.com/file/d/1n1ixctqPRoP6oHgfCResFexzRCEnc0TX/view?usp=drive_link" },
  { name: "🍿The Truman Show", url: "https://drive.google.com/file/d/1iN26Uy2fGADWSriX22ew84Ml0ODbUfJH/view?usp=drive_link" },
  { name: "🍿Bodyguard 1", url: "https://drive.google.com/drive/folders/1uXuU0VlmMPzDvB33Pc7WV7AX1o8rg0kY?usp=drive_link" },
  { name: "🍿Brickleberry", url: "https://drive.google.com/drive/folders/1h7fdWxz-h16nUgi1t67FP6mzRWqPU8X3" },
  { name: "🍿Dracula", url: "https://drive.google.com/drive/folders/10370h1IUbGQr4ne7cPPaBc3j1MYm5ZqJ?usp=drive_link" },
  { name: "🍿Glitch 1", url: "https://drive.google.com/drive/folders/1JppK6fSYZ9JqNgKvcvHLEcxtDbjC_S1X?usp=drive_link" },
  { name: "🍿October Faction 1", url: "https://drive.google.com/drive/folders/1NnZVci5OMqVkqf5Z4_8AifoejIc22AQV?usp=drive_link" },
  { name: "🍿Nadie Duerme En El Bosque Esta Noche 1", url: "https://drive.google.com/file/d/13j4N_GIiiQ1jMXK6Qt8M3CtW4dNEYs0q/view?usp=drive_link" },
  { name: "🍿It 2", url: "https://drive.google.com/file/d/14GrFzztS9HHqa2P4RkH-V9h1qiuxtVFX/view?usp=drive_link" },
  { name: "🍿Freak Este Cuerpo", url: "https://drive.google.com/file/d/13iRgw7BVOm4lmt5XiDK2T17t0HjmU_1N/view?usp=drive_link" },
  { name: "🍿Diavlo", url: "https://drive.google.com/file/d/13hnSXF1y8aDJyq6YWN1rOXbXL9hNA4Ju/view?usp=drive_link" },
  { name: "🍿Scream 5", url: "https://drive.google.com/file/d/14knB-PA5Ly_tUMMy-_uC73gsFl6LTDmg/view?usp=drive_link" },
  { name: "🍿Morbius", url: "https://drive.google.com/file/d/129RuomaMHYK9eIfJgeFCDtF6h-jIeD55/view?usp=drive_link" },
  { name: "🍿Agentes 355", url: "https://drive.google.com/file/d/14WDPbYpK1N3ZBTMr94ZJ-56XHNqEVcmf/view?usp=drive_link" },
  { name: "🍿Pasajero 666", url: "https://drive.google.com/file/d/13zUDizvM_UW8nVdbLfL9aGpTRCDKNyoV/view?usp=drive_link" },
  { name: "🍿Nadie Saldra Vivo De Aqui", url: "https://drive.google.com/file/d/13pq_yeT7FFaAS74i052imvMLqomiJFM9/view?usp=drive_link" },
  { name: "🍿Nadie Duerme En El Bosque Esta Noche 2", url: "https://drive.google.com/file/d/14K2-HaAmMxoU59D2UAFmJ5BE9COkfdpp/view?usp=drive_link" },
  { name: "🍿Amigos Pasajeros", url: "https://drive.google.com/file/d/13jbumkOFz0giBaDfFO-aDM24NT_ZBZ-E/view?usp=drive_link" },
  { name: "🍿WayDown", url: "https://drive.google.com/file/d/14F4B7ekTYxabxWpSTG0UEkn4dRU_0g9Q/view?usp=drive_link" },
  { name: "🍿Agente 007", url: "https://drive.google.com/file/d/14U9yhwDPwq4nyN1bFgbC0i8b6zCZsrX7/view?usp=drive_link" },
  { name: "🍿Kingsman 3", url: "https://drive.google.com/file/d/13oZQW10qJljhQbTQ_FgCflQwbgC_Bu2j/view?usp=drive_link" },
  { name: "🍿Nobody", url: "https://drive.google.com/file/d/13qHIyaVY3vvjNSBYS24acPVv0Ec_fcqm/view?usp=drive_link" },
  { name: "🍿Proyecto Adam", url: "https://drive.google.com/file/d/10ooZt7Wqu2bXkLRje4pSMYmeLtjV-mlH/view?usp=drive_link" },
  { name: "🍿Piratas", url: "https://drive.google.com/file/d/10_BswnPFU3sv13lTErADvK67BOSeqUre/view?usp=drive_link" },
  { name: "🍿Jackass X Siempre", url: "https://drive.google.com/file/d/10SantEDNivgzMYN_ooqEcxp6xiCXmM6I/view?usp=drive_link" },
  { name: "🍿No Exit", url: "https://drive.google.com/file/d/12fRuA6_po_A08rwsLwTsN1BqC-M3Job2/view?usp=drive_link" },
  { name: "🍿Masacre En Texas (2022)", url: "https://drive.google.com/file/d/10JB-GsQe3kpZgvb_HWqYDoNlBFI3Gajy/view?usp=drive_link" },
  { name: "🍿El Privilegio", url: "https://drive.google.com/file/d/10PB8uRdiJA5XXSB3sEUHAb--FzpeqgU3/view?usp=drive_link" },
  { name: "🍿The Other Bodyguard 2", url: "https://drive.google.com/file/d/11WYuLro00uQCKPP7ciXIHcWSkc3JAbr5/view?usp=drive_link" },
  { name: "🍿Salt", url: "https://drive.google.com/file/d/126c_mB1ZXf93AzknKM7ABUDfYhdt29cc/view?usp=drive_link" },
  { name: "🍿La Torre Oscura", url: "https://drive.google.com/file/d/12HqxFKRnjilVBIfusW7_gVQfCViPcs7x/view?usp=drive_link" },
  { name: "🍿Red Avispa", url: "https://drive.google.com/file/d/12dAkZ4nDgzZ3Z1-5DzGqP8gcWZtl4xuD/view?usp=drive_link" },
  { name: "🍿It 1", url: "https://drive.google.com/file/d/10fT6IJdUJ0SoddeXHIgw9ADhpE4GLDRw/view?usp=drive_link" },
  { name: "🍿I Am Mother", url: "https://drive.google.com/file/d/12A6IjbU-xKe7d8ae7bVQOI5QYSRfO5TI/view?usp=drive_link" },
  { name: "🍿Hotel Artemis", url: "https://drive.google.com/file/d/11WIF4c3f9xK8KlA0In7Qn2l3BAo8iT8G/view?usp=drive_link" },
  { name: "🍿Feliz Dia De Tu Muerte 2", url: "https://drive.google.com/file/d/11TRGbSpgvBc3AlsNm3mbOujAOcQnwvuU/view?usp=drive_link" },
  { name: "🍿Feliz Dia De Tu Muerte 1", url: "https://drive.google.com/file/d/11Ptgb8tl767dPOi0gQe7PlaDdwLJ0Hyu/view?usp=drive_link" },
  { name: "🍿Await Further Instructions", url: "https://drive.google.com/file/d/12azYX6YHmE_DeIfv6d8VsGxZXucAHPCd/view?usp=drive_link" },
  { name: "🍿Animales Fantasticos 2", url: "https://drive.google.com/file/d/12D3NG8qBwraAeqsRCvvVK4c8BnPPlizs/view?usp=drive_link" },
  { name: "🍿Amigos De Armas", url: "https://drive.google.com/file/d/12GhoGWmXXHhpjYrS_WaqHtyaVln8Bb1C/view?usp=drive_link" },
  { name: "🍿Muerte En El Nilo", url: "https://drive.google.com/file/d/12cfJQO8D6AstGbcugt4uer-wixpV24ZS/view?usp=drive_link" },
{ name: "🍿Una Noche A Tope", url: "https://drive.google.com/file/d/10-dUfRizmUcC3-nVNgBK2KW3W7VaXw__/view?usp=drive_link" },
{ name: "🍿Villanos", url: "https://drive.google.com/file/d/1044t8F6kcsFvclAKErt7Tn6U_Wlkb4VD/view?usp=drive_link" },
{ name: "🍿Quien Mato A Los Puppets", url: "https://drive.google.com/file/d/10IoY4It4l20uVO0snZEgTf1Ll8NkSo5l/view?usp=drive_link" },
{ name: "🍿My Hero Academia 1", url: "https://drive.google.com/file/d/10RfRlcVjmvQnrrYixFASpE0j7fx4otpF/view?usp=drive_link" },
{ name: "🍿My Hero Academia 2", url: "https://drive.google.com/file/d/10zLSehZyM8dkGYjObg_RfMLoCOnu8ar1/view?usp=drive_link" },
{ name: "🍿Lo Dejo Cuando Quiera", url: "https://drive.google.com/file/d/10Lp4DoPKtMFo121mGZuWb2oazgLiadnf/view?usp=drive_link" },
{ name: "🍿Colosal", url: "https://drive.google.com/file/d/10F928swVcoqAmOnOTAl6nLGx-O0-5mTb/view?usp=drive_link" },
{ name: "🍿Asesinato En El Oriente Expres", url: "https://drive.google.com/file/d/1-k-CQZYCQm7XihoTkGWn0NdfLLXnz9Ib/view?usp=drive_link" },
{ name: "🍿AmityVille", url: "https://drive.google.com/file/d/12NWGyTvChKkCK3O3nny7Ezw0qHktBu4c/view?usp=drive_link" },
{ name: "🍿A Rough Draft", url: "https://drive.google.com/file/d/1-xRUBtlQqDbHwnunijSQN3vlUO8rBAZa/view?usp=drive_link" },
{ name: "🍿Game Over", url: "https://drive.google.com/file/d/1FuU6US-x1SEitOPbCdxqEdqlM_gJWOK4/view?usp=drive_link" },
{ name: "🍿El Vecino", url: "https://drive.google.com/drive/folders/1Emc7AAbo-E8bKaKDR6T3CJe4BphIHAkP?usp=drive_link" },
{ name: "🍿WestWorld", url: "https://drive.google.com/drive/folders/16-ptJMA7SueN-U7QLh6cUb82lrXcLmY-?usp=drive_link" },
{ name: "🍿Raising Dion", url: "https://drive.google.com/drive/folders/1CgPvjrlap4EK-b3fS0L_sfcVYW-3CLBI?usp=drive_link" },
{ name: "🍿Los Enviados", url: "https://drive.google.com/drive/folders/1E54pLo2hz6z73TYaiYeYCZgYNJF0sV57?usp=drive_link" },
{ name: "🍿The Boys 2", url: "https://drive.google.com/drive/folders/16-DlxEaNQUNWeJIb3YsraN6fgvEyv0oj?usp=drive_link" },
{ name: "🍿Ataque De Titanes 4.2", url: "https://drive.google.com/drive/folders/1olCzkTE4MFORoNgXvSbu61BWnlSpDKW1" },
{ name: "🍿Esta Mierda Me Supera", url: "https://drive.google.com/drive/folders/158sUhUqc5sw9URq6hVklw5B-vT-wZxJN?usp=drive_link" },
{ name: "🍿El Legado De Jupiter", url: "https://drive.google.com/drive/folders/16NUaJrK_TAUQalIzw0fahTmn5vBurYaM?usp=drive_link" },
{ name: "🍿The End Of The Fucking World", url: "https://drive.google.com/drive/folders/150SMnaN-HMhAz-xL-Ns3BG-K8YLcK1S4?usp=drive_link" },
{ name: "🍿Shadow & Bone 1", url: "https://drive.google.com/drive/folders/10ha7QQ0zVjnb_S8AfQ3hf1wdlL2kgfKw?usp=drive_link" },
{ name: "🍿Mesias", url: "https://drive.google.com/drive/folders/17rAdZ7qCnyrAwY5D_05m_GvrzyI01C87?usp=drive_link" },
{ name: "🍿Suicide Squad 2", url: "https://drive.google.com/file/d/1-iMIm47ebtsf_jVogbLHhMtrf4d1prJR/view?usp=drive_link" },
{ name: "🍿Ni En Tus Sueños", url: "https://drive.google.com/file/d/1gA4Akmv6C9LDbiveQNN5dvk3gQcne39H/view?usp=drive_link" },
{ name: "🍿Jexi", url: "https://drive.google.com/file/d/1O3FQva3h74OaXNNWhplOHjQqcN35Wikh/view?usp=drive_link" },
{ name: "🍿Dr Strange 1", url: "https://drive.google.com/file/d/1tJZe2ukGzSa4IQkU66X2xqMJIe7iLA9R/view?usp=drive_link" },
{ name: "🍿El Conjuro 3", url: "https://drive.google.com/file/d/1GSRzAEWYkSrk6I3zAZ7ha0n6nmfLVpwQ/view?usp=drive_link" },
{ name: "🍿Doom Patrol", url: "https://drive.google.com/drive/folders/1hLoFdFiY8Na7iU-PypNlPZecTkKabAyg" },
{ name: "🍿Ataque De Titanes", url: "https://drive.google.com/drive/folders/1QVyd0JlP1wG9a40UgyLhOejZmUkfVTlH" },
{ name: "🍿Las Mil Caras De Dunjia", url: "https://drive.google.com/file/d/1IZCespPMwAHkweXK_DNxX9oBWHmX_pr5/view?usp=drive_link" },
{ name: "🍿Perfectos Desconocidos", url: "https://drive.google.com/file/d/1MqiwsJMSZrkNXkDRW0S8w-pY4PRZjLZ5/view?usp=drive_link" },
{ name: "🍿This Is America Mother Fucker", url: "https://drive.google.com/file/d/1wQgQe-CdVsXobrzzGFR-RT2YBGimQ-gv/view?usp=drive_link" },
{ name: "🍿El Pentavirato", url: "https://drive.google.com/drive/folders/153l-ZlNS7Sh1lbSj7V2eAbx1gSpz2aPW?usp=drive_link" },
{ name: "🍿What If", url: "https://drive.google.com/drive/folders/1IfMdHkAt7bkE3iLDeIwuHhVq_eTGD7IL?usp=drive_link" },
{ name: "🍿Mundos Paralelos", url: "https://drive.google.com/drive/folders/1ViysRW8wmVP93vTXRo4KBa3N8gMtLoXu?usp=drive_link" },
{ name: "🍿Desencanto 4", url: "https://drive.google.com/drive/folders/1HuRMpfgT9qC86Q6yar4TfUWE_UeAmv_R?usp=drive_link" },
{ name: "🍿Bang Bang Baby", url: "https://drive.google.com/drive/folders/16tux_yPRkcohCg5-EoLzUXlmjAyTgfp_?usp=drive_link" },
{ name: "🍿Ant Man 3", url: "https://u.pcloud.link/publink/show?code=XZiNwEVZjqeR2jk0INX6eUkQDLc420LmIs2V" },
{ name: "🍿One Punch Man 1", url: "https://u.pcloud.link/publink/show?code=kZ60xEVZyfwv7tnr0nYCKW1Y2PDY17abGhl7" },
{ name: "🍿Extraction 2", url: "https://u.pcloud.link/publink/show?code=XZvHeUVZpUPsOBHOtN7UfyH4zxQNvjt0fokX" },
{ name: "🍿Asterix y Obelix", url: "https://u.pcloud.link/publink/show?code=kZcAjX0ZczeInSdPm2QK84nOmFHrL0KSmEsk#folder=17575507142&tpl=publicfolderlist" },
{ name: "🍿Ghosted", url: "https://u.pcloud.link/publink/show?code=XZCOCEVZbLDvfRrfq4VSubMhUbx4Op7Y0Ohk" },
{ name: "🍿Replicas", url: "https://u.pcloud.link/publink/show?code=XZv9raVZlOY28EQi9JzTWWbJEjF5PYeX49bX" },
{ name: "🍿M3gan", url: "https://u.pcloud.link/publink/show?code=kZcAjX0ZczeInSdPm2QK84nOmFHrL0KSmEsk#folder=18517633812&tpl=publicfolderlist" },
{ name: "🍿Erase Una Vez Un Genio", url: "https://u.pcloud.link/publink/show?code=kZcAjX0ZczeInSdPm2QK84nOmFHrL0KSmEsk#folder=18517632659&tpl=publicfolderlist" },
{ name: "🍿Evil Dead 2", url: "https://u.pcloud.link/publink/show?code=XZqICEVZoIL5qU7iMWXRcNULUpBaK5Yu1Cj7" },
{ name: "🍿Tin y Tina", url: "https://u.pcloud.link/publink/show?code=XZIvCEVZNTR0Vnhp4cjRH2YmzSRY4buaGVdk" },
{ name: "🍿One Punch Man 2", url: "https://u.pcloud.link/publink/show?code=kZcAjX0ZczeInSdPm2QK84nOmFHrL0KSmEsk#folder=17574711090&tpl=publicfolderlist" },
{ name: "🍿One Punch Man Delux", url: "https://u.pcloud.link/publink/show?code=kZcAjX0ZczeInSdPm2QK84nOmFHrL0KSmEsk#folder=18239289585&tpl=publicfolderlist" },
{ name: "🎵CLOUD-MUSIC🎵", url: "https://drive.google.com/drive/folders/1-D6Lb9B1ye-5rdcAuREb4q7K5yRrikLT" },
{ name: "🍿13 Exorcismos", url: "https://u.pcloud.link/publink/show?code=XZAeKEVZucsrQ54LfpzdtGlJu0ApPJrIbPVk" },
{ name: "🍿Agente Stone", url: "https://u.pcloud.link/publink/show?code=XZEecNVZamvcPBJpfRYNtzDSXla7AB2DWrcX" },
{ name: "🍿Black Panter 2", url: "https://u.pcloud.link/publink/show?code=XZ4nKEVZRCEdMzuLDrzSJdJqeScQoyI0LgLy" },
{ name: "🍿Dungeons Dragons", url: "https://u.pcloud.link/publink/show?code=XZXowEVZvt4SFPoD0k7I1vUNbfykX7R3plNy" },
{ name: "🍿Fiesta En Casa", url: "https://drive.google.com/file/d/1_g86g8vkIK-wbgYvDYcffmxUWpCosnQO/view?usp=drive_link" },
{ name: "🍿El Exorcista Del Papa", url: "https://u.pcloud.link/publink/show?code=XZbowEVZVtmXMHifvYztkmsftG6pVukCm1mk" },
{ name: "🍿John Wick 4", url: "https://u.pcloud.link/publink/show?code=XZDowEVZEm8272IrlskJ5z4xnv94sBAHrkH7" },
{ name: "🍿Flash", url: "https://u.pcloud.link/publink/show?code=XZoJaAVZ0PRRbA0GK8B94yhtbqL8BFmVJBa7" },
{ name: "🍿Misterio A Bordo 2", url: "https://u.pcloud.link/publink/show?code=XZy7KEVZHgiwF4qq9zfIlXh0EQXAVp7Pqgjy" },
{ name: "🍿Llaman A La Puerta", url: "https://u.pcloud.link/publink/show?code=XZlowEVZIjj2sf3i3zbIz4P3AN13bXsDMQ6V" },
{ name: "🍿Hidden Strike", url: "https://u.pcloud.link/publink/show?code=XZBNyNVZyHn5xsNCKShMKiPwbjhiYje5boLV" },
{ name: "🍿Molino Rojo", url: "https://u.pcloud.link/publink/show?code=XZ9MlEVZCNNTJi5fAQpoPqNdqFKUSfqueWWV" },
{ name: "🍿Operacion Fortune", url: "https://u.pcloud.link/publink/show?code=XZXTlEVZV7fqMY24zdLg0x94n1q2j5RXsqEX" },
{ name: "🍿Shazam 2", url: "https://u.pcloud.link/publink/show?code=XZqTlEVZ1j44Lk0o5imYzk27kinoMSatfvnk" },
{ name: "🍿Un Fantasma Anda Suelto", url: "https://u.pcloud.link/publink/show?code=XZFPlEVZffzzD32Ynly9jab7YVtqv7dr7d7V" },
{ name: "🍿Avatar 2", url: "https://u.pcloud.link/publink/show?code=kZTNjX0ZjdQCFqW0qH0tgasAT8GwzmjYPtV7" },
{ name: "🍿Shadow & Bone 2", url: "https://u.pcloud.link/publink/show?code=kZCNjX0Z7XkulBXlfC4XDPaUkbRBGf7QUekX#folder=18239116584&tpl=publicfolderlist" },
{ name: "🍿1899", url: "https://drive.google.com/drive/folders/1pr9214boJD9fI0id23VkEEOPKHBlheS5?usp=drive_link" },
{ name: "🍿Dracula (2023)", url: "https://u.pcloud.link/publink/show?code=XZ1xX3VZN9Tl9R9U6F8Fw0TLKkH2qVQER3yy" },
{ name: "🍿Guardianes De La Galaxia 3", url: "https://u.pcloud.link/publink/show?code=XZqa4AVZGdsDrWjUhaXCDfPYCjJXLfd0k8rV" },
{ name: "🍿Transformers", url: "https://u.pcloud.link/publink/show?code=XZqumNVZwbgJ7vOrxqmkxWnNIQtMJBS1DKk0" },
{ name: "🍿Invasion Secreta", url: "https://u.pcloud.link/publink/show?code=kZI2eUVZD9fnGzKhGMQl5VvkXSaXV0SsNQck" },
{ name: "🍿Fast & Furious X", url: "https://u.pcloud.link/publink/show?code=XZmNkIVZ7mNF1SNQrt0C7ECSyuBHD4B04P1X" },
{ name: "🍿La Monja 1", url: "https://drive.google.com/file/d/10nxv0FnrSjXZuK5pUc-KUACUrsCoeJQV/view?usp=drivesdk" },
{ name: "🍿Insidious", url: "https://drive.google.com/drive/folders/1DsnVR6Ghss02MglOy-QCDHeUm49WROMj" },
{ name: "🍿The Witcher 3", url: "https://u.pcloud.link/publink/show?code=kZ27XIVZEYdMbcIjdxyvrBFfh63gkjAl1xmk" },
{ name: "🍿La Morgue De Jane Doe", url: "https://drive.google.com/file/d/1lhogHm_7ubvVk4E9-SXExZ7LhLEwlJHI/view?usp=drivesdk" },
{ name: "🍿Dulces y Sangrientos 16", url: "https://u.pcloud.link/publink/show?code=kZb3jX0ZAmM27kUHr1S9GGGGe8bmcQ5g2S9X" },
{ name: "🍿Mr Pickles 1", url: "https://u.pcloud.link/publink/show?code=kZocI3VZZTvc6Cyz1YMuvKon8v7OSjSm8ghVX" },
{ name: "🍿Mr Pickles 2", url: "https://u.pcloud.link/publink/show?code=kZPoI3VZEKVyKLhEAQSDMLrCTwhB7QaJC0M7" },
{ name: "🍿Mr Pickles 3", url: "https://u.pcloud.link/publink/show?code=kZJ1v3VZolLepF9CAOQdBDazraS5DYarFiNk" },
{ name: "🍿Berlin", url: "https://u.pcloud.link/publink/show?code=kZD3jX0Zl0BbQmnhm7RlgkTPG01Lt56WItLy#folder=20057957131&tpl=publicfolderlist" },
{ name: "🍿Gen V", url: "https://u.pcloud.link/publink/show?code=kZD3jX0Zl0BbQmnhm7RlgkTPG01Lt56WItLy#folder=19365851832&tpl=publicfolderlist" },
{ name: "🍿Loki 1", url: "https://u.pcloud.link/publink/show?code=kZD3jX0Zl0BbQmnhm7RlgkTPG01Lt56WItLy#folder=19034655840&tpl=publicfolderlist" },
{ name: "🍿Loki 2", url: "https://u.pcloud.link/publink/show?code=kZD3jX0Zl0BbQmnhm7RlgkTPG01Lt56WItLy#folder=19034656608&tpl=publicfolderlist" },
{ name: "🍿Invencible 2", url: "https://u.pcloud.link/publink/show?code=kZo6DR0Z1GGyIzSRXUL3v2BETPumt7fk03Xk" },
{ name: "🍿Doom Patrol 4.2", url: "https://u.pcloud.link/publink/show?code=kZP3jX0Zb4QGfXOSPk0kKEYVgoRLXjOxE9qV#folder=19398787915&tpl=publicfolderlist" },
{ name: "🍿La Rueda Del Tiempo 2", url: "https://u.pcloud.link/publink/show?code=kZP3jX0Zb4QGfXOSPk0kKEYVgoRLXjOxE9qV#folder=19103437309&tpl=publicfolderlist" },
{ name: "🍿Wanda Vision", url: "https://u.pcloud.link/publink/show?code=kZP3jX0Zb4QGfXOSPk0kKEYVgoRLXjOxE9qV#folder=19130274733&tpl=publicfolderlist" },
{ name: "🍿Moon Knight", url: "https://drive.google.com/drive/folders/18ONH2Re0ziD5LSbcPmr_Tci6Ucs9S5Uj?usp=drive_link" },
{ name: "🍿The Baby", url: "https://drive.google.com/drive/folders/14Y5QS-Np-2TUGkYWnHHn-kA_rH24yfdT?usp=drive_link" },
{ name: "🍿Elfen Lied", url: "https://drive.google.com/drive/folders/13GvyAU6xNwiphdwAvlebmE8nJQMunrht?usp=drive_link" },
{ name: "🍿The Banishing", url: "https://drive.google.com/file/d/17vrFrXExVfKHADXUM2IA3vEgfsG1_f3t/view?usp=drive_link" },
{ name: "🍿A Writer's Odyssey", url: "https://drive.google.com/file/d/18sbsvUCVSGAuGvcWyiML8bO0AHPzCJFM/view?usp=drive_link" },
{ name: "🍿Eliges O Mueres", url: "https://drive.google.com/file/d/1GGkQA-9L-eUC6RIBbird_VSXZg3pwHDD/view?usp=drive_link" },
{ name: "🍿Uncharted", url: "https://drive.google.com/file/d/14REzNCkTl3R8ZvJErE9VlGURtzWs8rx9/view?usp=drive_link" },
{ name: "🍿The Batman", url: "https://drive.google.com/file/d/189rmr58iv7OXgEyn1L1_c9Wyq4TpOgzp/view?usp=drive_link" },
{ name: "🍿El Sastre De La Mafia", url: "https://drive.google.com/file/d/184JCBm8XVlGPirasvZAOemQyhuQd2rAC/view?usp=drive_link" },
{ name: "🍿Abigail Disney", url: "https://drive.google.com/file/d/1GcQC0hbrVsFBlmxAAUSGFKWHmDvBH04P/view?usp=drive_link" },
{ name: "🍿The Witches", url: "https://drive.google.com/file/d/1Gb620tOqiPptds1oYCDMxd_PMf4CpK44/view?usp=drive_link" },
{ name: "🍿The Craft", url: "https://drive.google.com/file/d/1GXGSMeH-PlkP30MDtdvkel87Q1PUTDa_/view?usp=drive_link" },
{ name: "🍿Superagente Makey", url: "https://drive.google.com/file/d/1Nj6hvez2YanYFXCDzuZdF-PEUrumy75G/view?usp=drive_link" },
{ name: "🍿Promocion Fantasma", url: "https://drive.google.com/file/d/1Nrya_lSRu1t-09qe2Ojqld6L783TE1o5/view?usp=drive_link" },
{ name: "🍿El Misterio Del Dragon", url: "https://drive.google.com/file/d/1GiZM1IoXgwwDndouSzd_tuaADVNTXtSO/view?usp=drive_link" },
{ name: "🍿El Exorcismo De Dios", url: "https://drive.google.com/file/d/1hX6Zb1tp67RdSJFRbrW5E4TiOS2VFqUv/view?usp=drive_link" },
{ name: "🍿El Predicador", url: "https://drive.google.com/drive/folders/1-0eGrbLiq9Ki4HActJJGwHlmOclbV7uw?usp=drive_link" },
{ name: "🍿The Boys 1", url: "https://drive.google.com/drive/folders/1EVr2ZQu-YPz8arog7vbQgb2ttkGNs9II?usp=drive_link" },
{ name: "🍿The Umbrella Academy 3", url: "https://drive.google.com/drive/folders/1cBSlG4DXrJkEJqeKwkqd5lNGGBPWRr2E?usp=drive_link" },
{ name: "🍿The Boys Diabolical", url: "https://drive.google.com/drive/folders/1mLG5v3dcDtIuQ5dPAp9B-DZxHn9f7LT4?usp=drive_link" },
{ name: "🍿Spriggan", url: "https://drive.google.com/drive/folders/1mInA_0FLLMn9WjzxsRTHscLl6uktR-6_?usp=drive_link" },
{ name: "🍿Man Vs Bee", url: "https://drive.google.com/drive/folders/1sKS-_7Ubs8wqLYaAPNNUDEY6BlcXT1QS?usp=drive_link" },
{ name: "🍿American Horror Stories", url: "https://drive.google.com/drive/folders/1TzNHu1V4vVcPM1Nc4VVX9Fic_dTraEYL?usp=drive_link" },
{ name: "🍿Vampire In The Garden", url: "https://drive.google.com/drive/folders/1mKaZ2SLgTSH8bpL9oox9b7Ift_vWwK4F?usp=drive_link" },
{ name: "🍿Veneciafrenia", url: "https://drive.google.com/file/d/11qGeSeN04yA0QBtLa6nWJvCXU9mD4v-Z/view?usp=drive_link" },
{ name: "🍿The Night", url: "https://drive.google.com/file/d/1w5bw3jfWZnp0JtOzr_9DKALoSoPOyeIt/view?usp=drive_link" },
{ name: "🍿The Green Knight", url: "https://drive.google.com/file/d/1w2arpT9MeY0nsXWUbALjfNKajUKkjaXG/view?usp=drive_link" },
{ name: "🍿The Gray Man", url: "https://drive.google.com/file/d/1U-zBTivbIV4TniRoKnFMfCVz5MUJ-GXc/view?usp=drive_link" },
{ name: "🍿Separation", url: "https://drive.google.com/file/d/1QLEGLam05ed1Cwv88OrecDFI0r_AYb76/view?usp=drive_link" },
{ name: "🍿Escape Room (La Peli)", url: "https://drive.google.com/file/d/1DWyoXH_FRGsEaaNA8815mJ_9lJqYKDel/view?usp=drive_link" },
{ name: "🍿Prey", url: "https://drive.google.com/file/d/17UHXQdh_5N94Dq9pZOjGX6zGT-xGKUdR/view?usp=drive_link" },
{ name: "🍿Padre No Hay Mas Que Uno", url: "https://drive.google.com/file/d/1un7rrCA0z7h-bEfYz_YsYqBl8gZjy1uZ/view?usp=drive_link" },
{ name: "🍿Minions El Origen De Gru", url: "https://drive.google.com/file/d/1D5oefPY4C5-Yoc_6KIwMns0G6wGtqAW4/view?usp=drive_link" },
{ name: "🍿La Llamada Del Diablo", url: "https://drive.google.com/file/d/1QKKZSJITzyg8okkyjY5Np-r97_rAqpQa/view?usp=drive_link" },
{ name: "🍿Beavis & Butt", url: "https://drive.google.com/file/d/1Fyqy9RxN325jFxNMyW-6wmSsMXsoK813/view?usp=drive_link" },
{ name: "🍿Knives Out", url: "https://drive.google.com/file/d/1QCQY4kvI0UejtLDgUGmpWg10zNbkLdm7/view?usp=drive_link" },
{ name: "🍿Garra", url: "https://drive.google.com/file/d/1s0gaNqydo_Xp9yKGhd0j2M_OChrKVdZM/view?usp=drive_link" },
{ name: "🍿Freaks Out", url: "https://drive.google.com/file/d/1Paj9sgvGuoqhVPezU65K2y7xkhd1XCtL/view?usp=drive_link" },
{ name: "🍿El Hombre De Toronto", url: "https://drive.google.com/file/d/1uuS39rlhpo2VFwmAjLbP1_9lJVzHvpHy/view?usp=drive_link" },
{ name: "🍿Black Phone", url: "https://drive.google.com/file/d/1FpV9YLdKV6znRcKTNNz7qIGdmUmvAyRU/view?usp=drive_link" },
{ name: "🍿Shut In", url: "https://drive.google.com/file/d/1ZDmPsuYEz7--Cl-GKxTMeW4vC1d7gw9e/view?usp=drive_link" },
{ name: "🍿Ruega Por Nosotros", url: "https://drive.google.com/file/d/1B-YXQVjeYWmUoBg7NzOhju4yWyT6gFAd/view?usp=drive_link" },
{ name: "🍿Mira Por Mi", url: "https://drive.google.com/file/d/1E9sfAE82BsLFkmZdzrv9H9B_oHHoTRQo/view?usp=drive_link" },
{ name: "🍿Good Night Mommy", url: "https://drive.google.com/file/d/1DkxFmM-GeXVJSwZ7XczjcRrAp_l_pBdg/view?usp=drive_link" },
{ name: "🍿Good Mourning", url: "https://drive.google.com/file/d/15EpJ_ZR50BnQFPYvQJ6Uyt9oYhcQ-20o/view?usp=drive_link" },
{ name: "🍿Turno De Dia", url: "https://drive.google.com/file/d/1APtcxuWQwmZSCZwlu3Yl0RXzp-E_8SP4/view?usp=drive_link" },
{ name: "🍿Thor (Amor Y Odio)", url: "https://drive.google.com/file/d/1jGsqhx20NRDDjz6sU_NeXtxJ8O150HLD/view?usp=drive_link" },
{ name: "🍿The Equalizer 2", url: "https://drive.google.com/file/d/1FkE6rvmPJ0jvJy_ufTIa6chgf6E0Ag1a/view?usp=drive_link" },
{ name: "🍿Slumber Party Massacre", url: "https://drive.google.com/file/d/1E99MSsoliSqDWR6uWOa8zWbTVwU0WTpP/view?usp=drive_link" },
{ name: "🍿She Hulk", url: "https://drive.google.com/drive/folders/1IDx9KFezHncBckOxXF4k5hQUSQ2fRl6A?usp=drive_link" },
{ name: "🍿See 3", url: "https://drive.google.com/drive/folders/1EtGQjuEpTpYLFw3CyzhyTUEOO8vO5L_I?usp=drive_link" },
{ name: "🍿Sandman", url: "https://drive.google.com/drive/folders/13sOvXusbcPAn1sbLlUUCtwjT5XNJe2w7?usp=drive_link" },
{ name: "🍿Locke & Key 3", url: "https://drive.google.com/drive/folders/19R2D98Wtg1JYcPqkGABtjoV295waG9Ck?usp=drive_link" },
{ name: "🍿Justice Served", url: "https://drive.google.com/drive/folders/1pi7Ie0Y8mrPR0VlYoJUMX4vNJWnJWl2N?usp=drive_link" },
{ name: "🍿Good Omens", url: "https://drive.google.com/drive/folders/17JdweFzy46KrXJc0ZliCwOui15u2Td3A?usp=drive_link" },
{ name: "🍿Baki", url: "https://drive.google.com/drive/folders/11pVihRJilhIvOob7cpn55Xvp7Q4ps3Gi?usp=drive_link" },
{ name: "🍿Lupin", url: "https://drive.google.com/drive/folders/1sPdsKm3RTNJfb9S-7KnehK2VI6CP9orr?usp=drive_link" },
{ name: "🍿El Diablo En Ohio", url: "https://drive.google.com/drive/folders/1-QalcOGGPlpWPuETyl7w9-eoFZB30h3b?usp=drive_link" },
{ name: "🍿Anillos De Poder", url: "https://drive.google.com/drive/folders/1g4g0T7J5PEHzLBjl6SHwf3nXyP9sbYYj?usp=drive_link" },
{ name: "🍿La Pasajera", url: "https://drive.google.com/file/d/1AYqHJK9dl79ccjvIvyZGGU_UlPWLnZKG/view?usp=drive_link" },
{ name: "🍿La Invitacion", url: "https://drive.google.com/file/d/1BaDBkNRfNqkIFZZYsSPvMLoJyE3NVjCC/view?usp=drive_link" },
{ name: "🍿La Bestia", url: "https://drive.google.com/file/d/1JjQpZSdx5w5vFAVZcVhpN2gBybChOXRI/view?usp=drive_link" },
{ name: "🍿El Exorcismo De Mi Mejor Amiga", url: "https://drive.google.com/file/d/1zJtUmnBbG76bJgkCUKn_-IJnixNITCoG/view?usp=drive_link" }, 
{ name: "🍿The Skeleton Key", url: "https://drive.google.com/file/d/1Ju_1b_FnDTIHf-FlXGGB2NydRdcEyTvD/view?usp=drive_link" },
{ name: "🍿The Gentlemens", url: "https://drive.google.com/file/d/1rpQOIKmizYLLt2zpg_yxlQ87EJxM4McV/view?usp=drive_link" },
{ name: "🍿Maligno", url: "https://drive.google.com/file/d/1J_QXOeCBTdR6oklV_4Mj0xrJGBhTKaVq/view?usp=drive_link" },
{ name: "🍿Ghosts", url: "https://drive.google.com/drive/folders/1--zY-EDd-hEMXABqGu04OguwquiZeAlV" },
{ name: "🍿Marianne", url: "https://drive.google.com/drive/folders/1cAcwzT70xX6M--ZHZAuL37o9EVXk0Xr8?usp=drive_link" },
{ name: "🍿Merlina Addams", url: "https://drive.google.com/drive/folders/1ZkWRZfmVkzaUWAlhJa1ZMfpeK2ymxou8?usp=drive_link" },
{ name: "🍿The Bastard Son Of Devil", url: "https://drive.google.com/drive/folders/1cH0AN9kGdHLcwl2A_QPRcmU2PRpjdtDt?usp=drive_link" },
{ name: "🍿The Witcher 1", url: "https://drive.google.com/drive/folders/1lFHu58_VqsfM5RfiTRNWvMhm3PtOX72K?usp=drive_link" },
{ name: "🍿Black Adam", url: "https://drive.google.com/file/d/1ZbTKhTahcZ-CiflWiEziGOyezp7UTDHD/view?usp=drive_link" },
{ name: "🍿Como Me Convertí En Super", url: "https://drive.google.com/file/d/1NMGLj6Be_OXAy8UP93KpjfprhaoaYyHo/view?usp=drive_link" },
{ name: "🍿Lo Nunca Visto", url: "https://drive.google.com/file/d/1-Aj4Uj0S0aYCcQhenovfzLQyFrz9W7wm/view?usp=drive_link" },
{ name: "🍿American Gods", url: "https://drive.google.com/drive/folders/1si0pNAOVaYJD2rsfxW5nrWmtOYtKW3AM?usp=drive_link" },
{ name: "🍿Toc Toc", url: "https://drive.google.com/file/d/1pcRNL2NuWu2-qlXU8FnX0iy2aNissTir/view?usp=drive_link" },
{ name: "🍿El Hoyo", url: "https://drive.google.com/file/d/1Hl7TjdZBm8tanNCwB2_M8wEiCT_WHrAJ/view?usp=drive_link" },
{ name: "🍿El Reino Prohibido", url: "https://drive.google.com/file/d/10wgUEJ00CyCzEAc6n5OZaj9LR9ae-TRe/view?usp=drive_link" },
{ name: "🍿El Robo Del Siglo", url: "https://drive.google.com/file/d/1pTYYn0JdmX4H1SQCk9pox2hdAB-SMmGB/view?usp=drive_link" },
{ name: "🍿La Luz Del Diablo", url: "https://drive.google.com/file/d/1IBKlsFMuP562dCjZZxvp0r95skP9E6e7/view?usp=drive_link" },
{ name: "🍿Smile", url: "https://drive.google.com/file/d/1WmtIYWTQVOZuFZKY6JxjzWOKCld5ccdF/view?usp=drive_link" },
{ name: "🍿El País De Los Sueños", url: "https://drive.google.com/file/d/1hTGPQRTLc93R6uJJzP7tjLD8lCYPHWz_/view?usp=drive_link" },
{ name: "🍿Todo En Todas Partes", url: "https://drive.google.com/file/d/1X0bHXbFCa_AWoitWPjJT5B34xQd8acL4/view?usp=drive_link" },
{ name: "🍿El Menú", url: "https://drive.google.com/file/d/138nC-Omv-FUMpHuLPr9bc0zs9lh8Qyhe/view?usp=drive_link" },
{ name: "🍿Mañana Es Hoy", url: "https://drive.google.com/file/d/11fSUAb1HZVAMdiNgLoxhzEfTB6d_NZw3/view?usp=drive_link" },
{ name: "🍿Super Quien", url: "https://drive.google.com/file/d/13NGn13gLyB2598vpgrA-M8ScbEHWaum7/view?usp=drive_link" },
{ name: "🍿Witch Hunt", url: "https://drive.google.com/file/d/1SlcY_RaDstx4bn4T304Iiq8jCa2GItWZ/view?usp=drive_link" },
{ name: "🍿His Dark Materials 1", url: "https://drive.google.com/drive/folders/1f0HGb7hPrqdQGJySawmKXCp_Lohsyxr6?usp=drive_link" },
{ name: "🍿His Dark Materials 2", url: "https://drive.google.com/drive/folders/1NH6OgHkXftEsuL6HHodbKMdoMrtkLawj?usp=drive_link" },
{ name: "🍿His Dark Materials 3", url: "https://drive.google.com/drive/folders/1NRQXqvX11kGn7e3p7k-t8cf6zECUfb8z?usp=drive_link" },
{ name: "🍿Inside Job 2", url: "https://drive.google.com/drive/folders/1Xy_Lfl8u_j6fH4j7TUNNqnGlPApBExhx?usp=drive_link" },
{ name: "🍿Rick & Morty", url: "https://drive.google.com/drive/folders/1NZuy1mrY9a8GH7eMQBtPA-Tj5rxjwBW9?usp=drive_link" },
{ name: "🍿Margaux", url: "https://drive.google.com/file/d/1XUm9kautpuNED-h939sFEKLEXzSb9oWM/view?usp=drive_link" },
{ name: "🍿Pinocho", url: "https://drive.google.com/file/d/1KDdddn9KriaFfJ1zsZ0wA4b0f4WkdZcv/view?usp=drive_link" },
{ name: "🍿Los Renglones Torcidos De Dios", url: "https://drive.google.com/file/d/1BrwJQI6vxx3dswb-EqMaAojJG1_e5l3x/view?usp=drive_link" },
{ name: "🍿El Gabinete De Las Curiosidades", url: "https://drive.google.com/drive/folders/1RvI_Jq1jJQLtRI_GRxsrwQ2WrOSNH83g?usp=drive_link" },
{ name: "🍿RIP.D 1", url: "https://drive.google.com/file/d/1s7jdUOG4IbeY91H9Vbl3OMPwUb9J9O8_/view?usp=drive_link" },
{ name: "🍿RIP.D 2", url: "https://drive.google.com/file/d/1JLB42Zh7Em--kCQ5-jit7MumgZyTRwvp/view?usp=drive_link" },
{ name: "🍿The Boys 4", url: "https://drive.google.com/drive/folders/1-0m7g37ATJxxo1vJE57Bwc2uHML08asl" },
{ name: "🍿Aida", url: "https://drive.google.com/drive/folders/1xgNdigb3odRJLSi8pTh5LgN33dFIrar7?usp=drive_link" },
{ name: "🍿Hansel & Gretel", url: "https://drive.google.com/file/d/1wrBDHdOm6T4K-EeZc68ki2Cha3POXUgM/view?usp=drive_link" },
  { name: "🍿La Isla De La Fantasia", url: "https://drive.google.com/file/d/13-CJySAN1ENdto3P1hNXLDztSBmoJdya/view?usp=drive_link" },
  { name: "🍿La Liga De La Justicia", url: "https://drive.google.com/file/d/1wYogh5CN1jYnJDtwRLs-CqTHorm5EZfW/view?usp=drive_link" },
  { name: "🍿Malasaña 32", url: "https://drive.google.com/file/d/17h_p8JLSAUdHChxO6Eu4aFUqnsOL5M-E/view?usp=drive_link" },
  { name: "🍿All My Friends Are Dead", url: "https://drive.google.com/file/d/13vyDSwscSUiEcmReXHAk-0UfPzN_enmA/view?usp=drive_link" },
  { name: "🍿Stranger Things 3", url: "https://drive.google.com/drive/folders/153WqakVFQG8XSlxbZLBif6bv9oEMYyFW?usp=drive_link" },
  { name: "🍿Alita", url: "https://drive.google.com/file/d/17V6ANRL-o1Xgf9QbubGqd4bVJno1hFki/view?usp=drive_link" },
  { name: "🍿Boda Sangrienta", url: "https://drive.google.com/file/d/17J70IqKsedQdSs5X02LbSwLWYaLA6JJu/view?usp=drive_link" },
  { name: "🍿John Wick 2", url: "https://drive.google.com/file/d/18-E2f2OfhizfV01Vo7n_FlcklDXqF1Qo/view?usp=drive_link" },
  { name: "🍿John Wick 3", url: "https://drive.google.com/file/d/19nZ_o6zyfmhQeSa-RXKH8Pv_n2WOJ570/view?usp=drive_link" },
  { name: "🍿La Calle Del Terror 1994 (Parte 1)", url: "https://drive.google.com/file/d/17I2FkJPbsr9slrNTRaozaqRfEBKfNF44/view?usp=drive_link" },
  { name: "🍿La Calle Del Terror 1666 (Parte 3)", url: "https://drive.google.com/file/d/1eQ6kKPCsTTAeFnX1YBPrVvpsNOkYHz7X/view?usp=drive_link" },
  { name: "🍿Maestras Del Engaño", url: "https://drive.google.com/file/d/13bnv6Vnn7reULBO1rRzbg88L-sMgSB0X/view?usp=drive_link" },
  { name: "🍿Misterio A Bordo 1", url: "https://drive.google.com/file/d/12Mkx5mj1F4NAgg4WnkNSB_oxBNwurhN5/view?usp=drive_link" },
  { name: "🍿No Dormiras", url: "https://drive.google.com/file/d/19HVNsYh4UnOFkYz6LPX7WYCrM1sIbUvW/view?usp=drive_link" },
  { name: "🍿Love Death And Robot 2", url: "https://drive.google.com/drive/folders/12mvN2GK-dc6jRCyP7QREWV2dkLCc7GBl?usp=drive_link" },
  { name: "🍿Sky Rojo", url: "https://drive.google.com/drive/folders/10S594Np6EkL7plAU1eOo8-v748hCKsQ1?usp=drive_link" },
  { name: "🍿The Umbrella Academy", url: "https://drive.google.com/drive/folders/1-gJb71A-Ou7NwLO6tPoQ7QRehqU9RhM1?usp=drive_link" },
  { name: "🍿A Quiet Place 1", url: "https://drive.google.com/file/d/1pzpkAK9ZKaHDA6JKV-GYHHvboOixjn1F/view?usp=drive_link" },
  { name: "🍿A Quiet Place 2", url: "https://drive.google.com/file/d/1pxLUaGt-4G3_XuILYK6vBMnlphIhmnIR/view?usp=drive_link" },
  { NAME: "🍿Anna", URL: "https://drive.google.com/file/d/1JJCsu5kppnXT-SoQNr0Cfb-FwaCLANdr/view?usp=drive_link" },
  { NAME: "🍿Spell", URL: "https://drive.google.com/file/d/1CKziC_G6ycyKHaDi3srkFE3tWrBRz2r5/view?usp=drive_link" },
  { NAME: "🍿Disomnia", URL: "https://drive.google.com/file/d/1K3cqasxX1a8XhaYPQIh-MCVJOKlDYYva/view?usp=drive_link" },
  { NAME: "🍿The Others", URL: "https://drive.google.com/file/d/1IzkU4790L_aWObqu12h6UsItPuqAeBRL/view?usp=drive_link" },
  { NAME: "🍿Identity", URL: "https://drive.google.com/file/d/1pDdJrvpfpMd0jmTlgBu4OqlVKNLwnjhI/view?usp=drive_link" },
  { NAME: "🍿SuperIntelligence", URL: "https://drive.google.com/file/d/1Y-ecdtPOBv1DJIcgH5PI2a8eT5ZW1UJR/view?usp=drive_link" },
  { NAME: "🍿Maa", URL: "https://drive.google.com/file/d/1pP_dI2n-yTI34K0C4M2H4PCgvqUinlvZ/view?usp=drive_link" },
  { NAME: "🍿Todas Caen", URL: "https://drive.google.com/file/d/1Go_ft-oLszVS_VPZaKVV39SGRHtPBTsb/view?usp=drive_link" },
  { NAME: "🍿La Calle De Terror 1978 (Parte 2)", URL: "https://drive.google.com/file/d/17kIN60KEyZ_3v7TQrImBXYWC_oFtcEIH/view?usp=drive_link" },
  { NAME: "🍿La Clasica Historia De Terror", URL: "https://drive.google.com/file/d/1TUOH8ZAy0c-roOqiZZXNk9G1rFXFKjBZ/view?usp=drive_link" },
  { NAME: "🍿La Vieja Guardia", URL: "https://drive.google.com/file/d/12LT3wckxoFW6KvODmDYTdEsOjDd_vlvB/view?usp=drive_link" },
  { NAME: "🍿Ricos Y Mimados", URL: "https://drive.google.com/file/d/1-2qUrH62bqvkK-O1H7prhOXFuTaPrqpH/view?usp=drive_link" },
  { NAME: "🍿Space Jam", URL: "https://drive.google.com/file/d/1Vcr3aF7ofRYZlTxGEuc8Yo_11IYN9aT9/view?usp=drive_link" },
  { NAME: "🍿Black Widow", URL: "https://drive.google.com/file/d/18IQLrAeCn6zmzHgsjbS36hLI116Fqn9Q/view?usp=drive_link" },
  { NAME: "🍿G I Joe 2", URL: "https://drive.google.com/file/d/1GaHtGLgSafHTgDDvC9J0m8Bwjwafy043/view?usp=drive_link" },
  { NAME: "🍿G I Joe 1", URL: "https://drive.google.com/file/d/1GiB9FdVtXp4XjlPQBDy-kSG_KUj9YeZH/view?usp=drive_link" },
  { NAME: "🍿Ghost Shell", URL: "https://drive.google.com/file/d/17E8-Nf8UMqG8tIHuug22LLT2kzStQXb8/view?usp=drive_link" },
  { NAME: "🍿Justicia Implacable", URL: "https://drive.google.com/file/d/1XpmaZ2SRx0dzgA7z6BTyN8wmpm-YKhfi/view?usp=drive_link" },
  { NAME: "🍿Assassins Creed", URL: "https://drive.google.com/file/d/16svGfGuIzj-zeO0uth-BrnNBohuRRcCr/view?usp=drive_link" },
  { NAME: "🍿Desencanto 3", URL: "https://drive.google.com/drive/folders/19B9YAjCq3lnqyJjFo3AXLbO2qXLWpsji?usp=drive_link" },
{ NAME: "🍿Glitch 2-3", URL: "https://drive.google.com/drive/folders/115jVALMRLC5S4lqaDP9AcDhXBn_6GMsg?usp=drive_link" },
  { NAME: "🍿Annabelle 3", URL: "https://drive.google.com/file/d/1CdOP1-qBKj7b4AetZxEy9xMvF5rmS90u/view?usp=drive_link" },
  { NAME: "🍿Stranger Things", URL: "https://drive.google.com/drive/folders/1FQSWai0X8wxEBTj7nlvXTB9upTyFaLee?usp=drive_link" },
  { NAME: "🍿El Conjuro 2", URL: "https://drive.google.com/file/d/1BV3Xe0d2PLldPfvzuZRGHILUJi3udSMw/view?usp=drive_link" },
  { NAME: "🍿El Pasajero 1", URL: "https://drive.google.com/file/d/19iWo9OWy4Hx5O-l9Pid2vZbs3r_-t-FD/view?usp=drive_link" },
  { NAME: "🍿Los Tigres Del Tren", URL: "https://drive.google.com/file/d/1LYHJf2tdaNuAO_WgF03QSHjv3QC1nbQA/view?usp=drive_link" },
  { NAME: "🍿Noe", URL: "https://drive.google.com/file/d/17mY_FhXKmSpPM_IZ5ZsOhIQXG0DBAPkU/view?usp=drive_link" },
  { NAME: "🍿Ouija 2", URL: "https://drive.google.com/file/d/1Bs9kfcUHW6uFg8Zx7lUJ13_Mct_WNqDS/view?usp=drive_link" },
  { NAME: "🍿Proyecto Geminis", URL: "https://drive.google.com/file/d/198_7aNSEjHUWeeHcjIKeFoKq7nDJ5IEx/view?usp=drive_link" },
  { NAME: "🍿Descuida Yo Te Cuido", URL: "https://drive.google.com/file/d/1JSisTbMDiOHhc3ubIiWlxKNSxKmz33rg/view?usp=drive_link" },
  { NAME: "🍿Come Play", URL: "https://drive.google.com/file/d/1CSpzy9nAiz5bICsLG8XZzH9rDCiJ4nwT/view?usp=drive_link" },
  { NAME: "🍿Dolitle", URL: "https://drive.google.com/file/d/1Hz8tELR3nq2qR5KCnA5ec_EYFcctsnyA/view?usp=drive_link" },
  { NAME: "🍿Dark (Oscuridad)", URL: "https://drive.google.com/drive/folders/1-4GwvU0NZQC841VR5b_7tEgYz30OZCYh?usp=drive_link" },
  { NAME: "🍿Locke & Key 1", URL: "https://drive.google.com/drive/folders/15IEe0C_bEs_fI54JwfTLPyrP-Q57CHrN?usp=drive_link" },
  { NAME: "🍿Maldita 1 (Cursed)", URL: "https://drive.google.com/drive/folders/14Xa3euoVuJ00gRHw_NIx3ipnsKea_PPi?usp=drive_link" },
  { NAME: "🍿See 1", URL: "https://drive.google.com/drive/folders/17TLahMrCfdVIHYFoNEf7zlTXspwRBgFX?usp=drive_link" },
  { NAME: "🍿See 2x08 Final", URL: "https://drive.google.com/file/d/183SLvLe-Kj-Gc3sHtQDWfBx2LYSLRRK9/view?usp=drive_link" },
  { NAME: "🍿Attraction 1", URL: "https://drive.google.com/file/d/1cRJinsdJrMlkL5Gn4NWYl4ZJhaJ5kdU_/view?usp=drive_link" },
  { NAME: "🍿Attraction 2", URL: "https://drive.google.com/file/d/1cQsahyX8kpkC4iScw_fiLB-ZKc9CmAGC/view?usp=drive_link" },
  { NAME: "🍿Aladdin", URL: "https://drive.google.com/file/d/19lyBfXFx4tN9bOF9lEfaa0UPCkKeZZ3n/view?usp=drive_link" },
  { NAME: "🍿The Boys 3", URL: "https://drive.google.com/drive/folders/1ZlPMgvfE9iWXnC04PSfJQTAbI0xT6Mxy" },
  { NAME: "🍿Invencible 1", URL: "https://drive.google.com/drive/folders/11ifcfWpqqv8NcsGQN-ka9n5dooQtD-Fy?usp=drive_link" },
  { NAME: "🍿Ragnarok (Manga)", URL: "https://drive.google.com/drive/folders/1T1XBBMU_Nf1h3uP_QtwRrZZpz3oCUkCB?usp=drive_link" },
  { NAME: "🍿Cielo Rojo Sangre", URL: "https://drive.google.com/file/d/1CV1K-A4P-u6ATn9ZwZxhHJGcsJf0hglQ/view?usp=drive_link" },
  { NAME: "🍿Escuela Para Fracasados", URL: "https://drive.google.com/file/d/1EBOaTI6Z9qPylUwfgbXveJwf0EyREOUi/view?usp=drive_link" },
  { NAME: "🍿Exam", URL: "https://drive.google.com/file/d/1FwQleXRn1mEPMz7dZy02VJPIZrcBX7Dy/view?usp=drive_link" },
  { NAME: "🍿Fast & Furious 9", URL: "https://drive.google.com/file/d/1hRwf_PGfuvssWFEmt549vYKGR7lOrAic/view?usp=drive_link" },
  { NAME: "🍿FlatLiners", URL: "https://drive.google.com/file/d/19GN9piSvoLyI3o-Snm0NefiIBq_BxDlB/view?usp=drive_link" },
  { NAME: "🍿Gangsterdam", URL: "https://drive.google.com/file/d/1F9NLphAKeJN7-asUwbHV3YEKEfVuy-Kf/view?usp=drive_link" },
  { NAME: "🍿I Frankestein", URL: "https://drive.google.com/file/d/19PwuHZhAy_TSUcH9LrITGd_c3OmBClws/view?usp=drive_link" },
  { NAME: "🍿Idiocracy", URL: "https://drive.google.com/file/d/1A_7eADKwqq9mmqYYJM6o-JNaJgbKZnU6/view?usp=drive_link" },
  { NAME: "🍿Jolt", URL: "https://drive.google.com/file/d/1O3_SqWCy9nfbJn3YDU-wfFTsQs1cGyO0/view?usp=drive_link" },
  { NAME: "🍿Juguetes Del Terror", URL: "https://drive.google.com/file/d/1QJjf3eD4QJvEbh-fJutIMNDj5SqzqTkl/view?usp=drive_link" },
  { NAME: "🍿Justo En La Mira", URL: "https://drive.google.com/file/d/1Ik2hSXldW2enNN_zv96HPMBlvVw9bARa/view?usp=drive_link" },
  { NAME: "🍿Mision Submarino", URL: "https://drive.google.com/file/d/1IaaDH-F_L0FhBIGH70SzOLk1EVNuRqZP/view?usp=drive_link" },
  { NAME: "🍿Para Toda La Muerte", URL: "https://drive.google.com/file/d/1E5hvpFX3hDRK_5zlhUDkp45L9cyZKJ6N/view?usp=drive_link" },
  { NAME: "🍿Queen Of Spades", URL: "https://drive.google.com/file/d/14zz9KcMBiZy65qIre8-IhRPk12K3rGAV/view?usp=drive_link" },
  { NAME: "🍿South Park 1 Post Covid", URL: "https://drive.google.com/file/d/1K3WLCwPLL-gXm7Z_tyRg3mXvlSTgO8pv/view?usp=drive_link" },
  { NAME: "🍿Animales Fantasticos 3", URL: "https://drive.google.com/file/d/1Mox6s3q0VMflHKnWeacOJZxekYbvnYEy/view?usp=drive_link" },
  { NAME: "🍿The House", URL: "https://drive.google.com/file/d/17bIvBRDyKiwkxswDTcHcu_LnuMafhgpz/view?usp=drive_link" },
  { NAME: "🍿The Mummy", URL: "https://drive.google.com/file/d/1CIACwvtWe4y2m_4v-28XqYxzYtaNnWT8/view?usp=drive_link" },
  { NAME: "🍿The Other Bodyguard 1", URL: "https://drive.google.com/file/d/1PO9itknk_ptZ56TjXKNJ4R44JcpsjDSH/view?usp=drive_link" },
  { NAME: "🍿Winchester", URL: "https://drive.google.com/file/d/16vEtXqseuW4fRWGWzDHVEpy034ddw3tY/view?usp=drive_link" },
  { NAME: "🍿Black Mirror", URL: "https://drive.google.com/drive/folders/1l7zbz6BmPeuDy-wUD5zalr7Wzff6UdD6?usp=drive_link" },
  { NAME: "🍿Aida 5", URL: "https://drive.google.com/drive/folders/1-8Skdo4D5fcRMAo9AwrFK-1TbRYFGm1o?usp=drive_link" },
 { NAME: "🍿Feria", URL: "https://u.pcloud.link/publink/show?code=kZe7zb0ZhM3frcxWmmjQrx4vp3qQMLCiavM7#folder=21724266003&tpl=publicfoldergrid" },
  { NAME: "🍿El Problema De Los 3 Cuerpos", URL: "https://u.pcloud.link/publink/show?code=kZe7zb0ZhM3frcxWmmjQrx4vp3qQMLCiavM7#folder=21193801742&tpl=publicfoldergrid" },
  { NAME: "🍿Atom Eve", URL: "https://share.vidyard.com/watch/uzF7WK6uYXPnQ7Ld7KWZVq?autoplay=1" },
  { NAME: "🍿La Sociedad Americana De Negros Magicos", URL: "https://u.pcloud.link/publink/show?code=XZdkdB0ZlLNo2InvaXRxGK3K0qfI7pq9MNnk" },
  { NAME: "🍿Die Hart 2", URL: "https://u.pcloud.link/publink/show?code=XZE94s0Z8iWOAMbAAjz6k1TY1kzo2uUddDUV" },
  { NAME: "🍿Sentencia De Muerte (Beekeeper)", URL: "https://u.pcloud.link/publink/show?code=XZwfl40ZWTA1uCF2Fkf0lGD9hdOuy71y43J7" },
  { NAME: "🍿Avatar The Last AirBender", URL: "https://u.pcloud.link/publink/show?code=kZlCub0ZggmeCSMu8AH4eEKOq03YaJEYsQuX#folder=22064707390&tpl=publicfoldergrid" },
  { NAME: "🍿BagHead", URL: "https://u.pcloud.link/publink/show?code=XZTaLh0ZLlefprzN92Q9fwlHUHm4r43o2j8k" },
  { NAME: "🍿Damsel", URL: "https://u.pcloud.link/publink/show?code=XZgf6b0ZyFzTokBxspHlNRu2smI0KSW0pRAV" },
  { NAME: "🍿Die Hart 1", URL: "https://u.pcloud.link/publink/show?code=XZtm8s0ZseM5DB9ByKL1amwFX4opmjAwxGIX" },
  { NAME: "🍿Citadel 1", URL: "https://drive.google.com/drive/folders/131eNGxfwhwZa8X8ITm2HXgb3hIh8FMQE?usp=drive_link" },
  { NAME: "🍿Penny Dreadful", URL: "https://drive.google.com/drive/folders/1JujLRY854GDDhj4j45azIz_nbMoMoj84?usp=drive_link" },
  { NAME: "🍿SpiderWick Chronicles", URL: "https://drive.google.com/drive/folders/1bD4f2PzhLmFRTmolJK2M5dTe9otD4lvq?usp=drive_link" },
  { NAME: "🍿El Septimo Hijo", URL: "https://share.vidyard.com/watch/FgnhzVqz3puayFQd93ZTSc?autoplay=1" },
  { NAME: "🍿Nunca Me Encontraras", URL: "https://share.vidyard.com/watch/ds3ivhpMYv2rtiVXQ9jWES?autoplay=1" },
  { NAME: "🍿Black Friday", URL: "https://share.vidyard.com/watch/GgnhpxV27gPbwwp55zGx94?autoplay=1" },
  { NAME: "🍿Lift", URL: "https://share.vidyard.com/watch/2VwBjc6uMy49NxtC2ueB3U?autoplay=1" },
  { NAME: "🍿Contra Todos", URL: "https://share.vidyard.com/watch/eza4vjVDwzoof7JW1xw33N?autoplay=1" },
  { NAME: "🍿El Primer Amen", URL: "https://share.vidyard.com/watch/AFhHLkS77N3KRuffLd8eQY?autoplay=1" },
  { NAME: "🍿Atlas", URL: "https://share.vidyard.com/watch/u5RmAERC77LwCU9EgCps55?autoplay=1" },
  { NAME: "🍿Logan Wolverine", URL: "https://share.vidyard.com/watch/FSZJHaWsX3xEEwo7oyCqTp?autoplay=1" },
  { NAME: "🍿Dune 2", URL: "https://share.vidyard.com/watch/zRUp4igoEaiQNd42oK2nbJ?" },
  { NAME: "🍿No Tengas Miedo", URL: "https://share.vidyard.com/watch/F9kTdpRdfELWKvGSQZVrS1?" },
  { NAME: "🍿The Creator", URL: "https://share.vidyard.com/watch/9rFjJx4Q886KrLDF2wXy9r?" },
  { NAME: "🍿El Gato Con Botas", URL: "https://share.vidyard.com/watch/DgGzfbZ5VAPwAYcwcpamtU?" },
  { NAME: "🍿The Equalizer 3", URL: "https://share.vidyard.com/watch/s2anhRuF3shTtiut39y9xB?" },
  { NAME: "🍿Five Nights At Freddys", URL: "https://share.vidyard.com/watch/rxE8eJVLCv5Da67ksXxrrj?" },
  { NAME: "🍿Caceria En Venecia", URL: "https://share.vidyard.com/watch/SPuKBKqxeE6TGQ2g1T3Se3?" },
  { NAME: "🍿Mision Imposible 7.1", URL: "https://share.vidyard.com/watch/jieofkcScoE1B41ayxXjuL?" },
  { NAME: "🍿Life", URL: "https://share.vidyard.com/watch/vdWBBcNVRjEZkB2dzr3cxp?" },
  { NAME: "🍿La Puerta Secreta", URL: "https://share.vidyard.com/watch/QjPKP24o93Qw2AJec69Vbu?" },
  { NAME: "🍿Saw X", URL: "https://share.vidyard.com/watch/S7YKk81VTunmAMhERQfwDs?" },
  { NAME: "🍿El Exorcista (2023)", URL: "https://share.vidyard.com/watch/Zt1ZsRqQKz51SBqaLjrSYp?" },
  { NAME: "🍿Hypnotic", URL: "https://share.vidyard.com/watch/VjYVzUJKApZVDsPkvTiRGG?" },
  { NAME: "🍿La Mansion Encantada", URL: "https://share.vidyard.com/watch/NGvaen3n4VvQyyxv9gjkxD?" },
  { NAME: "🍿Relive", URL: "https://share.vidyard.com/watch/AnfQ6XWnvJmsebhvBtYWsq?" },
  { NAME: "🍿Renfield", URL: "https://share.vidyard.com/watch/8cqJsPGrSHBrkJsksYHrun?" },
  { NAME: "🍿Desencanto 1-2", URL: "https://drive.google.com/drive/folders/131eJb8PVBJBDbpKyIv9-26XGNriTXXkB?usp=drive_link" },
  { NAME: "🍿HellHole", URL: "https://share.vidyard.com/watch/rPFxHKNYu2hfALQ8Hy2vQo?" },
  { NAME: "🍿Nadie Podra Salvarte", URL: "https://share.vidyard.com/watch/vhw4LKK5oSMXUQrzSCNXoS?" },
  { NAME: "🍿Blue Beetle", URL: "https://share.vidyard.com/watch/SL1UZVdhC1QU3NGPVxUhA9?" },
  { NAME: "🍿Kong & Godzilla", URL: "https://share.vidyard.com/watch/P26AgMCzz3HjYDJi7uZ9Ty?" },
  { NAME: "🍿The Marvels", URL: "https://share.vidyard.com/watch/xYErcRHDxHjJuYiSWk9RR7?" },
  { NAME: "🍿Rebel Moon 2", URL: "https://share.vidyard.com/watch/Mydq1NQAvgAprbDHWgD3q8?" },
  { NAME: "🍿Abigail", URL: "https://share.vidyard.com/watch/GpdE61ctqbCG3RLkb5e8M7?" },
  { NAME: "🍿Madame Web", URL: "https://share.vidyard.com/watch/weoJnhEoiSaVrQcDHjmGfq?" },
  { NAME: "🍿La Conferencia", URL: "https://share.vidyard.com/watch/AcDSU1LJ6uXoM9MEoSGShQ?" },
  { NAME: "🍿The Kill Room", URL: "https://share.vidyard.com/watch/GLo4iVfnCRonYYiR6gZ46u?" },
  { NAME: "🍿Los Asesinos De La Luna", URL: "https://share.vidyard.com/watch/SuF5iq3pYAd4jxiHYfWmLQ?" },
  { NAME: "🍿Aquaman 2", URL: "https://share.vidyard.com/watch/PRtyAVEbYJrMx7UYaunx3F?" },
  { NAME: "🍿Cadaver", URL: "https://share.vidyard.com/watch/yNED9KjYVAJoKVbkTJ4w7i?" },
  { NAME: "🍿South Park 3", URL: "https://share.vidyard.com/watch/nmQrZQ9hw3SoaNv8tH6QAA?" },
  { NAME: "🍿Relax", URL: "https://share.vidyard.com/watch/nhgsRUm9QAFKAe6BXRRRqU?" },
  { NAME: "🍿Rebel Moon 1", URL: "https://share.vidyard.com/watch/zNcp4aTyGgDEK4tjCW5FQH?" },
  { NAME: "🍿Hablame", URL: "https://share.vidyard.com/watch/niKdokT7vVJ7t7CSDenH3s?" },
  { NAME: "🍿Dejar El Mundo Atras", URL: "https://share.vidyard.com/watch/DNxNXVHrfEHq9cSQCxTctX?" },
  { NAME: "🍿El Hogar De Miss Peregrine", URL: "https://share.vidyard.com/watch/r2e6DWBtAitdL6xVLqHYYa?" },
  { NAME: "🍿Jung_E", URL: "https://share.vidyard.com/watch/YTDDHKX1ot4LAwatHYiBhe?" },
  { NAME: "🍿Venus", URL: "https://share.vidyard.com/watch/k4hDVazRShTurPR2Wm9vmi?" },
  { NAME: "⚙️La Movie Apps⚙️", URL: "https://u.pcloud.link/publink/show?code=kZlCub0ZggmeCSMu8AH4eEKOq03YaJEYsQuX#folder=22071115816&tpl=publicfoldergrid" },
  { NAME: "🍿Futurama", URL: "https://drive.google.com/drive/folders/1-aiBDqtDm8F3aqzWS68VA0TIKn_lEdbI" },
  { NAME: "🍿Avengers End Game", URL: "https://drive.google.com/file/d/102H5bd-h4_BIII9bqhH89huFYhaPEI9P/view?usp=drivesdk" },
  { NAME: "🍿Asylum", URL: "https://drive.google.com/file/d/1lYiJZNYv83lutXM_I4EMe_vT-WszAhM-/view?usp=drivesdk" },
  { NAME: "🍿HellBoy", URL: "https://drive.google.com/file/d/11ezbIXCh-G8XGanfdBkcBTEuaK6t_zqC/view?usp=drive_link" },
  { NAME: "🍿Spiderman No Way Home", URL: "https://drive.google.com/file/d/11pHR3sxk-Yb7meZqbz8RD5nMVhb-Rx46/view?usp=drive_link" },
  { NAME: "🍿No Mires Arriba", URL: "https://drive.google.com/file/d/11vYw1DB7nuDExNvvn5-ZqAyU5zD8Sk_d/view?usp=drive_link" },
  { NAME: "🍿The Witcher 2", URL: "https://drive.google.com/folderview?id=1ofhqc_aF5qVWEUgH1aIc1SE4eiIqvMOZ" },
  { NAME: "🍿El Sistema K E OPS", URL: "https://drive.google.com/file/d/1MUgaQtz6J5wJ49G844VDOye8Ri4Y31-g/view?usp=drive_link" },
  { NAME: "🍿Dr Strange 2", URL: "https://drive.google.com/file/d/1vlScjrLRWtTFG-Dqu8uz6KdejL1HHZbq/view?usp=drive_link" },
  { NAME: "🍿La Ciudad Perdida", URL: "https://drive.google.com/file/d/1RWp8IIMnufsftfDbEXo038ID9qLqaCIi/view?usp=drive_link" },
  { NAME: "🍿Memory", URL: "https://drive.google.com/file/d/1R8J_tzvdzbKs34LdQlPavCdnbuPuXc4E/view?usp=drive_link" },
  { NAME: "🍿Tren Bala", URL: "https://drive.google.com/file/d/1DaT8euWjr84q2nG3DtCQYaapRac-dFHS/view?usp=drive_link" },
  { NAME: "🍿Inception", URL: "https://drive.google.com/file/d/1hV6eC_ca5HaVi02E0xCS4c2J-Zcgj_Te/view?usp=drive_link" },
  { NAME: "🍿Locke & Key 2", URL: "https://drive.google.com/folderview?id=1pDyCtIehdTkSn920uIxMhtdHWhkkUvPa" },
  { NAME: "🍿La Casa De Papel Corea", URL: "https://drive.google.com/drive/folders/10AGbUu5SLvghM9xkqn7GZY87yegFgqZg?usp=drive_link" },
  { NAME: "🍿La Periferia", URL: "https://drive.google.com/drive/folders/1NNNu6w15tggKaUmPuK7CDwKFAOmN6NIS?usp=drive_link" },
  { NAME: "🍿Willow", URL: "https://drive.google.com/drive/folders/1eN-xMI3WGWrsDtJvjtRe_NAfijbOsMcF?usp=drive_link" },
  { NAME: "🍿The Witcher El Origen", URL: "https://drive.google.com/drive/folders/1s3zdBbZRCa_JX1CJ1b5ohdwFUXR9B40g?usp=drive_link" },
  { NAME: "🍿GhostBusters", URL: "https://drive.google.com/file/d/1GjcBxPWTq-fQAYzid2x9mJBAX73RA12m/view?usp=drive_link" },
  { NAME: "🍿Stranger Things 4", URL: "https://drive.google.com/drive/folders/1QaqhtNVHSKjm9JpDTsQrToFOoIHbTylI" },
  { NAME: "🍿WestWorld 4", URL: "https://drive.google.com/drive/folders/1xza8b-oJev3i3m9J8_hboSB5JDg_lssZ" },
  { NAME: "🍿Love Death And Robot 1", URL: "https://drive.google.com/drive/folders/1JE_stMQdixzGOwDaOm4ip0F6MsZTGcjA" },
  { NAME: "🍿Love Death And Robot 3", URL: "https://drive.google.com/drive/folders/1JJdQXs30vfZ-JP1sU3prrqD1qKPDI51c" },
  { NAME: "🍿Inside Job 1", URL: "https://drive.google.com/drive/folders/1seR4MPUA5WDyJQceb_SBzbtFeTDzLCA8" },
  { NAME: "🍿El Juego Del Calamar", URL: "https://drive.google.com/drive/folders/1HpOPpxhGqiMCO9Xphh9PdsT9kyhucy6C" },
  { NAME: "🍿La Casa De Papel 5.1", URL: "https://drive.google.com/drive/folders/1-X2MLSZdtYfProOFIV02G1trzTCqD7gJ" },
  { NAME: "🍿Fauces De La Noche", URL: "https://drive.google.com/file/d/1rUOwWmzY0anQmQGgG6aT9r7wcUPd6WMv/view?usp=drivesdk" },
  { NAME: "🍿See 2", URL: "https://drive.google.com/drive/folders/1qfteKvFm4i0WkKTR58FILA2DXyuKtdEn" },
  { NAME: "🍿Alerta Roja", URL: "https://drive.google.com/file/d/1GXTGu6-u2tfNpVLIMe2cQopnHTGLT3K4/view?usp=drivesdk" },
  { NAME: "🍿Dune 1", URL: "https://drive.google.com/file/d/1pzFLZwwmmIVERWVWGpBY5qQbVCLK--kJ/view?usp=drivesdk" },
  { NAME: "🍿Hipnotico", URL: "https://drive.google.com/file/d/1rUk3v2LS8lc0hJYnc0iWkwiMJOQlVZ_d/view?usp=drivesdk" },
  { NAME: "🍿La Hierba Alta", URL: "https://drive.google.com/file/d/14xqPt1BKTORRLwXUu1G2kJbVZizMdGsy/view?usp=drivesdk" },
  { NAME: "🍿La Leyenda De Los Diez Anillos", URL: "https://drive.google.com/file/d/1RXgrXUVk6OgZ-4iq5rlq1ijpKmQ54v1N/view?usp=drivesdk" },
  { NAME: "🍿Mortal Kombat", URL: "https://drive.google.com/file/d/15_bZQwUDQ_gowPfazzVED7YTo1naUw5a/view?usp=drivesdk" },
  { NAME: "🍿The House Next Door", URL: "https://drive.google.com/file/d/1XXuLDeqV6xqeC_AAkLsAJoD68L0FRaSz/view?usp=drivesdk" },
  { NAME: "🍿Venom 2", URL: "https://drive.google.com/file/d/1psSUnjkUb-aOYxdJv1r4Uzm4nUD8seWH/view?usp=drivesdk" },
  { NAME: "🍿Polaroid", URL: "https://drive.google.com/file/d/1bFae8drGS9nSR1O0TV_bCpjkhHg7KaAa/view?usp=drivesdk" },
  { NAME: "🍿Annabelle 2", URL: "https://drive.google.com/file/d/1-6i8ffNMlZl5b9J-FAxRauGodyIU6XcV/view?usp=drivesdk" },
  { NAME: "🍿A Ciegas", URL: "https://drive.google.com/file/d/1-12F5HL5JJPPQufZfNNU6guSE8ocdSSz/view?usp=drivesdk" },
  { NAME: "🍿Escape Room 2", URL: "https://drive.google.com/file/d/1U7MQOs62aFnScbDJqj5dgMb5KPONO60W/view?usp=drivesdk" },
  { NAME: "🍿La Hora De Tu Muerte", URL: "https://drive.google.com/file/d/1-5VfDw2Ij076BJWqDu-u5lR4ft1aIKaq/view?usp=drivesdk" }, 
  { NAME: "🍿Si No Despierto", URL: "https://vimeo.com/565171606" },
  { NAME: "🍿Dr Sueño", URL: "https://drive.google.com/file/d/10YkLs2TaXWYN_TOLTEZVBgdnJ1QH04mI/view?usp=drivesdk" },
  { NAME: "🍿Jack El Caza Gigantes", URL: "https://drive.google.com/file/d/10P5GvZnsxF9svYCi6dlHUdeVcha0d8lN/view?usp=drivesdk" },
  { NAME: "🍿Geotormenta", URL: "https://drive.google.com/file/d/10X21ZKVSBhcRCSFjaHt-LhCApMSgxjP1/view?usp=drivesdk" },
  { NAME: "🍿Kingsman 1", URL: "https://drive.google.com/file/d/108vQFtcd8-N1mbTLHb5DqKIU_SJRGBaf/view?usp/drivesdk" },
  { NAME: "🍿Kingsman 2", URL: "https://drive.google.com/file/d/1-_CqjxhKKTISJ_k7fMZZyFT3FVMDqygY/view?usp.sug" },
  { NAME: "🍿Mama O Papa", URL: "https://drive.google.com/file/d/13Mcr2JWeYJ13t0FmtMKYLPMtARyKPmsz/view?usp=drivesdk" },
  { NAME: "🍿Resident Evil", URL: "https://drive.google.com/file/d/1-Sl2gzf4NiyPuQadBvWIvkcb4JrI3y7p/view?usp=drivesdk" },
  { NAME: "🍿Imaginario", URL: "https://u.pcloud.link/publink/show?code=XZSVNR0ZsRoxywYzNLuDXGotKMCaSRb2LARy" },
  { NAME: "🍿La Monja 2", URL: "https://u.pcloud.link/publink/show?code=XZMJbiVZ2ysLWtLqjvyYfR9siJQVRJgpU1p7" },
  { NAME: "🍿Madre Androide", URL: "https://drive.google.com/file/d/15vB1YAdyImhtboPr7DZgvKGfn9kIIsywA/view?usp=drivesdk" },
  { NAME: "🍿Old (Viejo)", URL: "https://drive.google.com/file/d/1ttiXVylblbagn978HOffB2FzoNhL5k0M/view?usp=drivesdk" },
  { NAME: "🍿Rumbo Al Infierno", URL: "https://drive.google.com/drive/folders/10ZKyHSmKpyxX6fZC3JgS4pn3gx1wXw2P" },
  { NAME: "🍿DeepCity", URL: "https://drive.google.com/file/d/1-S1cQIEkaOhWvUtNegdJxEaYIWeXj-WH/view?usp=drivesdk" },
  { NAME: "🍿Oxigeno", URL: "https://drive.google.com/file/d/1-0za_QIpC4pDzV6jSQC_cSO1UWVhjduc/view?usp/drivesdk" },
  { NAME: "🍿Super Me", URL: "https://drive.google.com/file/d/10SomjYz_PneoLmeydTr4q5cZppBVbFde/view?usp=drivesdk" },
{ NAME: "🍿Matrix Resurrections", URL: "https://drive.google.com/file/d/1-4Y3E42uALIeiCtl3UD1nyHm_Q7Yj8b1/view?usp=drivesdk" },
{ NAME: "🍿Held", URL: "https://drive.google.com/file/d/1B2LwKRkcyDnJWK2a8MhkJDufw6FRLK1N/view?usp=drivesdk" },
{ NAME: "🍿Dr Brain", URL: "https://drive.google.com/drive/folders/1mr2LJZ9RQM6_DwFVovGwKFrZ4LBiRCgb" },
{ NAME: "🍿La Casa De Papel 5.2", URL: "https://drive.google.com/drive/folders/1YkejexkdMr0wn6J0Dt1UdVqxEc9stv3t" },
{ NAME: "🍿Super Crooks", URL: "https://drive.google.com/drive/folders/1b07buXbscHTDh88azuy7n6K85qybHl-U" },
{ NAME: "🍿La Rueda Del Tiempo 1", URL: "https://drive.google.com/drive/folders/1-Hec_SSWsm2ctbiSxUVCl96VmN3KyyZO" },
{ NAME: "🍿Asylum Horror Tales", URL: "https://drive.google.com/file/d/1lXmq-Jn_KHQTRoqeEBd8ML60wIHMr_Lb/view?usp=drivesdk" },
{ NAME: "🍿Donde Caben Dos", URL: "https://drive.google.com/file/d/1j3CSilpfM8dvaW6baZULHpwRXzgE3T0H/view?usp=drivesdk" },
{ NAME: "🍿G I Joe 3 Snake Eyes", URL: "https://drive.google.com/file/d/1ev-voXNqhdUzOQ5u7JURiTEGTtpiE2qn/view?usp=drivesdk" },
{ NAME: "🍿Vampiros Vs El Bronx", URL: "https://drive.google.com/file/d/1l9vJJEfDNNzp00Rb429CVc0Wvt4vRqT0/view?usp=drivesdk" },
{ NAME: "🍿La Mujer Maravilla 1", URL: "https://drive.google.com/file/d/1-slWJEMQjqWmcf-ZbRG3ICWpskHduibf/view?usp=drivesdk" },
{ NAME: "🍿La Mujer Maravilla 2", URL: "https://drive.google.com/file/d/10NA4QvX0Gr2F7T0dU_j2tjGo5vMRPMAz/view?usp=drivesdk" },
{ NAME: "🍿Ready Player One", URL: "https://drive.google.com/file/d/1K0LY5HidsPc0CKhg2DYjOzpjnJ-zvzMp/view?usp=drivesdk" },
{ NAME: "🍿Eternals", URL: "https://drive.google.com/file/d/1KLq6NADghQJ08M-agO_7YLqoXSxtDEup/view?usp=drivesdk" },
{ NAME: "🍿Argylle", URL: "https://u.pcloud.link/publink/show?code=XZ7Q5p0ZfuR2eQraE15pJ9ngFkVwg0dyHf6k" },
{ NAME: "🍿Expend4bles", URL: "https://vimeo.com/875398889?share=copy" },
{ NAME: "🍿Escuadron 6", URL: "https://drive.google.com/file/d/1KTy1otFV2kP7TjnARhfsiaJvBJFfbeOi/view?usp=drivesdk" },
{ NAME: "🍿Hitman", URL: "https://vimeo.com/565184591" },
  { NAME: "🍿Fiesta De Empresa", URL: "https://drive.google.com/file/d/14tCq2VlhiP78KL4-V5uiFLH2y5-0OhLx/view?usp=drivesdk" },
  { NAME: "🍿South Park (2024)", URL: "https://u.pcloud.link/publink/show?code=XZ4wF20ZdEbHXVuD6EQ8VkM5FFGvnBgGO5MX" },
  { NAME: "🍿Hotel Transylvania 4", URL: "https://drive.google.com/file/d/14n-3SiNFegq-50WqJ0EddfmisBoV-d9q/view?usp=drivesdk" },
  { NAME: "🍿Los Locos Addams 2", URL: "https://drive.google.com/file/d/127f2MOqAviF3fiNXP0ewXu6EA3nCqmCR/view?usp.com/file/d/127f2MOqAviF3fiNXP0ewXu6EA3nCqqCR/view?usp=drivesdk" },
  { NAME: "🍿Un Detective Suelto En Hollywood 4", URL: "https://share.vidyard.com/watch/goaK9CpkwALc6wMALX8XWq?" },
  { NAME: "📺Universal Tv", URL: "https://imagenuniversaltv.net:3771/live/iutvlive.m3u8" },
  { NAME: "📺IPTV", URL: "https://lamovie.github.io/IPTV/" },
  { NAME: "🍿Observados", URL: "https://drive.google.com/file/d/1JSub0W-ieTSGolShmHgYHYeOzn9Qwiq2/view?usp=drivesdk" },
  { NAME: "🍿Evil Dead 1", URL: "https://drive.google.com/file/d/1NCDSC_xcgQnH-X-EiToNlG5b6ldbVCfr/view?usp=drivesdk" },
  { NAME: "🍿El Bar", URL: "https://drive.google.com/file/d/1PnObRCUoUECtB-TMNE7TBgrTInQl76T9/view?usp=drivesdk" },
  { NAME: "🍿Verdad O Reto", URL: "https://drive.google.com/file/d/1hMBpk83kbgUUa-4-pdMuyGIkAcXJgg4J/view?usp=drivesdk" },
  { NAME: "🍿Heroes", URL: "https://lamovie.github.io/HEROES/" },
  { NAME: "🍿El Astronauta", URL: "https://drive.google.com/file/d/1jqHmSdsdd1SyvqJuHhwp9B5x4E4QaR5n/view?usp=drivesdk" },
  { NAME: "🍿Bad Boys 4", URL: "https://drive.google.com/file/d/1kDpXxuLzNpR4GqLFKYq_3ZIVItSEmDNy/view?usp:drivesdk" },
  { NAME: "🍿Deadpool 3", URL: "https://drive.google.com/file/d/1X8lkdllwCh1Fm53iMg-24fsq0irex8UA/view?usp=drivesdk" },
  { NAME: "🍿Umbrella Academy 4", URL: "https://drive.google.com/drive/folders/1DGkZqf7DPtm-6mJJzdQGNlD95H-oPOYG" },
  { NAME: "📺Dark Play Tv", URL: "https://lamovie.github.io/DARK-TV/" },
  { NAME: "📺Bass Nation Tv", URL: "https://lamovie.github.io/BASS-NATION-TV/" },
  { NAME: "📺X Tv", URL: "https://lamovie.github.io/X-TV-/" },
  { NAME: "🍿Mi Villano Favorito 4", URL: "https://drive.google.com/file/d/1JHxuQ54F182yR5L2gW0A4Zr1M2cveHpV/view?usp=drivesdk" },
  { NAME: "🍿A Quiet Place 3", URL: "https://drive.google.com/file/d/14gGqw3swLR5cQQGWihePubMRSQ2bRRuz/view?usp=drivesdk" },
    { NAME: "🍿Jackpot", URL: "https://drive.google.com/file/d/1uouT0f5TZkIf1LlcUvb3tLZP-fY5YKwB/view?usp=drivesdk" },
    { NAME: "🍿Longlegs El Coleccionista De Almas", URL: "https://drive.google.com/file/d/1LfsWbb-mTU4dAlzbxiA_luijxn0GsgjU/view?usp=drivesdk" },
    { NAME: "🍿La Trampa", URL: "https://drive.google.com/file/d/1DJLbYQdjGhw3rfhNxITsujKNiWrItzVO/view?usp=drivesdk" },
    { NAME: "🍿Late Night With The Devil", URL: "https://drive.google.com/file/d/1vd5CthQTgfHJnhJPd6ZH0dG70L1L2uRv/view?usp=drivesdk" },
    { NAME: "🍿El Hombre De Los Sueños", URL: "https://drive.google.com/file/d/1k808AShst6k1eLfvBbnlxScEypxFxttL/view?usp=drivesdk" },
    { NAME: "🍿The Killer", URL: "https://drive.google.com/file/d/15Xxhy5gW39sWXJB65cyZYNFNxfCJHEGe/view?usp=drivesdk" },
    { NAME: "🍿Kaos", URL: "https://drive.google.com/drive/folders/18djiKUm4Znpv9fpptyWa9He0na4xBxey" },
    { NAME: "🍿Anillos De Poder 2", URL: "https://drive.google.com/drive/folders/1AeP5Qb-w6Zb15w2joUHCLEN1WhK0loac" },
    { NAME: "🍿Agatha En Todas Partes 1", URL: "https://drive.google.com/drive/folders/1Eb0Hqh5ciz_lriSqSBWcfP9NWTECv9t9" },
    { NAME: "🍿Parpadea Dos Veces", URL: "https://drive.google.com/file/d/1KXDO89HmDOjYf7Zmw83G54qW6nIiNcUM/view?usp=drivesdk" },
    { NAME: "🍿El Hoyo 2", URL: "https://drive.google.com/file/d/1TC0MlmPnBVvddiRVL07IBiUeyRXebtqp/view?usp=drivesdk" },
    { NAME: "🍿Salem s Lot", URL: "https://drive.google.com/file/d/1tByfyOr1-bEfUgbWARhcSVHBDyPx5P-j/view?usp=drivesdk" },
    { NAME: "🍿No Te Sueltes", URL: "https://drive.google.com/file/d/1eZBWXV0e4H8CdDhFYfMxB7_oPAOX88ky/view?usp=drivesdk" },
    { NAME: "🍿Hellboy 4", URL: "https://drive.google.com/file/d/1um6g1ATDsUX1seOn1s_k41raQkeQP6K_/view?usp=drivesdk" },
    { NAME: "🍿Smile 2", URL: "https://drive.google.com/file/d/1hImOW7eNLN5fGLZyDXMCBvD6UpuC_yyQ/view?usp=drivesdk" },
    { NAME: "🍿Beetlejuice 2", URL: "https://drive.google.com/file/d/1P6v-hetMpopMjz_SWeD7TKm9J7wve0Ct/view?usp=drivesdk" },
    { NAME: "🍿Alice", URL: "https://drive.google.com/file/d/10Hv-B3zOtGj85FUOXIo3FQFn9Ti_QkIr/view?usp=drivesdk" },
    { NAME: "🍿From", URL: "https://drive.google.com/drive/folders/1IMyk5TgrACc3_HDMQDFAqCaOvY2O6qlA" },
    { NAME: "🍿Avengers La Era De Ultron", URL: "https://drive.google.com/file/d/1mWUVNFyGjPSceiRu7Jj12msIaZRdYbqn/view?usp=drivesdk" },
    { NAME: "🍿Aida 6", URL: "https://drive.google.com/drive/folders/1WiGhKEqkjqXIS9NwWdUAPGbZ4yXbBscZ" },
    { NAME: "🍿Aida 8", URL: "https://drive.google.com/drive/folders/1yPCOh-1_Apnx_1U7w0_BdOG5AQYg3MJ0" },
    { NAME: "🍿Mas Dura Sera La Caida", URL: "https://drive.google.com/file/d/1YN3y0cDubKVSZGNykXrIsVyf1fRALOBP/view?usp=drivesdk" },
    { NAME: "🍿Venom 3", URL: "https://drive.google.com/file/d/1ZjWemm3wMKkjs4k3YSVb2F1QeVUMYppi/view?usp=drivesdk" },
    { NAME: "🍿Un Rey En La Habana", URL: "https://drive.google.com/file/d/1liAuNkkrDf-eUm0vcCau_tspejvG0LfT/view?usp=drivesdk"},
    { NAME: "🍿Agentes Del Desorden", URL: "https://drive.google.com/file/d/10j-eMI6Z1bBW3gdU8rk9gerV9e4pe6S4/view?usp=drivesdk"}
];

// Selecciona la lista existente
var lista = document.getElementById("Lista");
 
// Agrega los nuevos elementos dinámicamente
Lista2.forEach(item => {
  var li = document.createElement("li");
  var a = document.createElement("a");

  a.href = item.URL || item.url;
  a.textContent = item.NAME || item.name;
  a.classList.add("Data");

  li.appendChild(a);
  lista.appendChild(li);
});

